project_id = "fgksnveweiwmovouflgj"

[functions.pubmed-search]
verify_jwt = false

[functions.import-icd]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.pathology-analyzer]
verify_jwt = false

[functions.cross-data-analyzer]
verify_jwt = false

[functions.deep-research]
verify_jwt = false
