-- Add detailed_analysis column to discovery_hypotheses table
-- This column stores thesis-level analysis generated by Claude

ALTER TABLE discovery_hypotheses 
ADD COLUMN IF NOT EXISTS detailed_analysis JSONB DEFAULT NULL;

-- Comment for documentation
COMMENT ON COLUMN discovery_hypotheses.detailed_analysis IS 'Thesis-level detailed analysis with background_context, pathophysiology, mechanism_of_action, literature_synthesis, clinical_implications, research_gaps, key_evidence_summary';
