-- ============================================
-- DISCOVERY PLATFORM SCHEMA
-- Tables for medical discovery platform
-- ============================================

-- 1. Papers Table (literature from PubMed, Europe PMC, etc.)
CREATE TABLE IF NOT EXISTS discovery_papers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pmid TEXT UNIQUE,
    pmcid TEXT,
    doi TEXT,
    title TEXT NOT NULL,
    authors JSONB DEFAULT '[]'::jsonb,
    abstract TEXT,
    publication_date DATE,
    journal TEXT,
    source TEXT NOT NULL CHECK (source IN ('pubmed', 'europepmc', 'pmc', 'clinicaltrials', 'openalex', 'crossref')),
    text_chunks JSONB DEFAULT '[]'::jsonb, -- [{chunk_id, text, section, offsets}]
    metadata JSONB DEFAULT '{}'::jsonb,
    full_text_available BOOLEAN DEFAULT FALSE,
    citation_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for efficient lookups
CREATE INDEX IF NOT EXISTS idx_discovery_papers_pmid ON discovery_papers(pmid) WHERE pmid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_discovery_papers_doi ON discovery_papers(doi) WHERE doi IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_discovery_papers_source ON discovery_papers(source);
CREATE INDEX IF NOT EXISTS idx_discovery_papers_publication_date ON discovery_papers(publication_date);

-- 2. Evidence Snippets Table (extracted passages from papers)
CREATE TABLE IF NOT EXISTS discovery_evidence_snippets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paper_id UUID REFERENCES discovery_papers(id) ON DELETE CASCADE,
    chunk_id TEXT,
    passage TEXT NOT NULL,
    section TEXT, -- 'abstract', 'introduction', 'methods', 'results', 'discussion'
    entities JSONB DEFAULT '[]'::jsonb, -- Detected entities (genes, proteins, drugs, diseases)
    claim_tags TEXT[] DEFAULT ARRAY[]::TEXT[], -- 'INHIBITS', 'ACTIVATES', 'ASSOCIATED_WITH', etc.
    confidence REAL DEFAULT 0.5,
    start_offset INTEGER,
    end_offset INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discovery_snippets_paper ON discovery_evidence_snippets(paper_id);
CREATE INDEX IF NOT EXISTS idx_discovery_snippets_entities ON discovery_evidence_snippets USING GIN(entities);
CREATE INDEX IF NOT EXISTS idx_discovery_snippets_claim_tags ON discovery_evidence_snippets USING GIN(claim_tags);

-- 3. Knowledge Graph Triples (extracted relations)
CREATE TABLE IF NOT EXISTS discovery_kg_triples (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subject_id TEXT NOT NULL,
    subject_type TEXT NOT NULL, -- 'GENE', 'PROTEIN', 'DRUG', 'DISEASE', 'PATHWAY', 'PHENOTYPE'
    subject_name TEXT NOT NULL,
    relation TEXT NOT NULL, -- 'INHIBITS', 'ACTIVATES', 'TREATS', 'CAUSES', 'ASSOCIATED_WITH'
    object_id TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_name TEXT NOT NULL,
    context JSONB DEFAULT '{}'::jsonb, -- {species, tissue, model, conditions}
    provenance UUID[] DEFAULT ARRAY[]::UUID[], -- References to evidence_snippets
    confidence_score REAL DEFAULT 0.5,
    evidence_level TEXT CHECK (evidence_level IN ('in_vitro', 'in_vivo', 'clinical', 'meta_analysis', 'unknown')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(subject_id, relation, object_id)
);

CREATE INDEX IF NOT EXISTS idx_discovery_triples_subject ON discovery_kg_triples(subject_id, subject_type);
CREATE INDEX IF NOT EXISTS idx_discovery_triples_object ON discovery_kg_triples(object_id, object_type);
CREATE INDEX IF NOT EXISTS idx_discovery_triples_relation ON discovery_kg_triples(relation);

-- 4. Evidence Packs (assembled context for Claude)
CREATE TABLE IF NOT EXISTS discovery_evidence_packs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query_intent JSONB NOT NULL, -- {disease, target, focus, keywords}
    paper_ids UUID[] DEFAULT ARRAY[]::UUID[],
    snippet_ids UUID[] DEFAULT ARRAY[]::UUID[],
    graph_neighborhood JSONB DEFAULT '{}'::jsonb, -- {nodes, edges}
    trials_context JSONB DEFAULT '[]'::jsonb,
    total_papers INTEGER DEFAULT 0,
    total_snippets INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discovery_packs_intent ON discovery_evidence_packs USING GIN(query_intent);

-- 5. Hypotheses (generated by Claude)
CREATE TABLE IF NOT EXISTS discovery_hypotheses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hypothesis_id TEXT UNIQUE NOT NULL, -- 'HYP-2024-001'
    statement TEXT NOT NULL,
    predictions JSONB DEFAULT '[]'::jsonb, -- Array of testable predictions
    minimal_tests JSONB DEFAULT '[]'::jsonb, -- [{type, description, materials, expected_outcome}]
    risks_confounders TEXT[] DEFAULT ARRAY[]::TEXT[],
    evidence_pack_id UUID REFERENCES discovery_evidence_packs(id),
    evidence_citations JSONB DEFAULT '[]'::jsonb, -- [{pmid, doi, snippet_id, quote}]
    scores JSONB DEFAULT '{}'::jsonb, -- {novelty, plausibility, strength, feasibility, impact, total}
    adversarial_review JSONB DEFAULT NULL, -- {counter_arguments, limitations, conclusion}
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'validated', 'rejected', 'testing', 'archived')),
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by UUID REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_discovery_hypotheses_status ON discovery_hypotheses(status);
CREATE INDEX IF NOT EXISTS idx_discovery_hypotheses_user ON discovery_hypotheses(user_id);
CREATE INDEX IF NOT EXISTS idx_discovery_hypotheses_scores ON discovery_hypotheses USING GIN(scores);

-- 6. Research Sessions (audit trail)
CREATE TABLE IF NOT EXISTS discovery_research_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    session_type TEXT NOT NULL CHECK (session_type IN ('search', 'hypothesis_generation', 'adversarial_review', 'full_discovery')),
    query TEXT,
    parameters JSONB DEFAULT '{}'::jsonb,
    results_summary JSONB DEFAULT '{}'::jsonb, -- {paper_count, hypothesis_count, duration_ms}
    claude_prompt TEXT,
    claude_response TEXT,
    tokens_used JSONB DEFAULT '{}'::jsonb, -- {input, output, total}
    duration_ms INTEGER,
    success BOOLEAN DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discovery_sessions_user ON discovery_research_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_discovery_sessions_type ON discovery_research_sessions(session_type);
CREATE INDEX IF NOT EXISTS idx_discovery_sessions_date ON discovery_research_sessions(created_at);

-- 7. API Cache (for rate limiting and deduplication)
CREATE TABLE IF NOT EXISTS discovery_api_cache (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cache_key TEXT UNIQUE NOT NULL, -- Hash of request params
    source TEXT NOT NULL, -- 'pubmed', 'europepmc', 'clinicaltrials', 'openalex'
    request_params JSONB NOT NULL,
    response_data JSONB NOT NULL,
    etag TEXT,
    last_modified TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days'),
    hit_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discovery_cache_key ON discovery_api_cache(cache_key);
CREATE INDEX IF NOT EXISTS idx_discovery_cache_source ON discovery_api_cache(source);
CREATE INDEX IF NOT EXISTS idx_discovery_cache_expires ON discovery_api_cache(expires_at);

-- 8. Discovery Alerts (for continuous discovery pipeline)
CREATE TABLE IF NOT EXISTS discovery_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL CHECK (type IN ('new_evidence', 'contradiction', 'high_impact', 'breakthrough')),
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    title TEXT NOT NULL,
    message TEXT,
    papers TEXT[] DEFAULT ARRAY[]::TEXT[],
    query TEXT,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by UUID REFERENCES auth.users(id),
    acknowledged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discovery_alerts_type ON discovery_alerts(type);
CREATE INDEX IF NOT EXISTS idx_discovery_alerts_severity ON discovery_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_discovery_alerts_acknowledged ON discovery_alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_discovery_alerts_created ON discovery_alerts(created_at);

-- ============================================
-- RLS POLICIES
-- ============================================

-- Enable RLS
ALTER TABLE discovery_papers ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_evidence_snippets ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_kg_triples ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_evidence_packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_hypotheses ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_research_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_api_cache ENABLE ROW LEVEL SECURITY;

-- Papers: Public read, admin write
CREATE POLICY "discovery_papers_read" ON discovery_papers FOR SELECT USING (true);
CREATE POLICY "discovery_papers_insert" ON discovery_papers FOR INSERT WITH CHECK (true);
CREATE POLICY "discovery_papers_update" ON discovery_papers FOR UPDATE USING (true);

-- Evidence Snippets: Public read
CREATE POLICY "discovery_snippets_read" ON discovery_evidence_snippets FOR SELECT USING (true);
CREATE POLICY "discovery_snippets_insert" ON discovery_evidence_snippets FOR INSERT WITH CHECK (true);

-- KG Triples: Public read
CREATE POLICY "discovery_triples_read" ON discovery_kg_triples FOR SELECT USING (true);
CREATE POLICY "discovery_triples_insert" ON discovery_kg_triples FOR INSERT WITH CHECK (true);
CREATE POLICY "discovery_triples_update" ON discovery_kg_triples FOR UPDATE USING (true);

-- Evidence Packs: Public read
CREATE POLICY "discovery_packs_read" ON discovery_evidence_packs FOR SELECT USING (true);
CREATE POLICY "discovery_packs_insert" ON discovery_evidence_packs FOR INSERT WITH CHECK (true);

-- Hypotheses: User-specific
CREATE POLICY "discovery_hypotheses_read" ON discovery_hypotheses FOR SELECT USING (true);
CREATE POLICY "discovery_hypotheses_insert" ON discovery_hypotheses FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "discovery_hypotheses_update" ON discovery_hypotheses FOR UPDATE USING (auth.uid() = user_id OR user_id IS NULL);

-- Research Sessions: User-specific
CREATE POLICY "discovery_sessions_read" ON discovery_research_sessions FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "discovery_sessions_insert" ON discovery_research_sessions FOR INSERT WITH CHECK (true);

-- API Cache: Service role only via Edge Functions (no direct user access)
CREATE POLICY "discovery_cache_read" ON discovery_api_cache FOR SELECT USING (true);
CREATE POLICY "discovery_cache_insert" ON discovery_api_cache FOR INSERT WITH CHECK (true);
CREATE POLICY "discovery_cache_update" ON discovery_api_cache FOR UPDATE USING (true);
CREATE POLICY "discovery_cache_delete" ON discovery_api_cache FOR DELETE USING (true);

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Function to generate hypothesis ID
CREATE OR REPLACE FUNCTION generate_hypothesis_id()
RETURNS TEXT AS $$
DECLARE
    year_part TEXT;
    seq_part TEXT;
    count INTEGER;
BEGIN
    year_part := TO_CHAR(NOW(), 'YYYY');
    SELECT COUNT(*) + 1 INTO count 
    FROM discovery_hypotheses 
    WHERE hypothesis_id LIKE 'HYP-' || year_part || '-%';
    seq_part := LPAD(count::TEXT, 3, '0');
    RETURN 'HYP-' || year_part || '-' || seq_part;
END;
$$ LANGUAGE plpgsql;

-- Function to clean expired cache
CREATE OR REPLACE FUNCTION cleanup_discovery_cache()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM discovery_api_cache WHERE expires_at < NOW();
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate hypothesis_id
CREATE OR REPLACE FUNCTION set_hypothesis_id()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.hypothesis_id IS NULL OR NEW.hypothesis_id = '' THEN
        NEW.hypothesis_id := generate_hypothesis_id();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_hypothesis_id
    BEFORE INSERT ON discovery_hypotheses
    FOR EACH ROW
    EXECUTE FUNCTION set_hypothesis_id();

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION update_discovery_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_papers_timestamp
    BEFORE UPDATE ON discovery_papers
    FOR EACH ROW
    EXECUTE FUNCTION update_discovery_timestamp();

CREATE TRIGGER trigger_update_hypotheses_timestamp
    BEFORE UPDATE ON discovery_hypotheses
    FOR EACH ROW
    EXECUTE FUNCTION update_discovery_timestamp();

CREATE TRIGGER trigger_update_triples_timestamp
    BEFORE UPDATE ON discovery_kg_triples
    FOR EACH ROW
    EXECUTE FUNCTION update_discovery_timestamp();

CREATE TRIGGER trigger_update_cache_timestamp
    BEFORE UPDATE ON discovery_api_cache
    FOR EACH ROW
    EXECUTE FUNCTION update_discovery_timestamp();
