-- Migration: semantic_graph_cache
-- Purpose: Cache generated graph nodes to avoid regenerating with Claude

-- Create table for caching semantic graph results
CREATE TABLE IF NOT EXISTS semantic_graph_cache (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic TEXT NOT NULL,
    topic_normalized TEXT NOT NULL,
    nodes JSONB NOT NULL DEFAULT '[]'::jsonb,
    edges JSONB NOT NULL DEFAULT '[]'::jsonb,
    sources_consulted JSONB DEFAULT '[]'::jsonb,
    is_comorbidity BOOLEAN DEFAULT FALSE,
    pathologies JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    hit_count INTEGER DEFAULT 0,
    generation_time_ms INTEGER,
    UNIQUE(topic_normalized)
);

-- Index for fast topic lookup
CREATE INDEX IF NOT EXISTS idx_semantic_graph_topic_normalized 
ON semantic_graph_cache(topic_normalized);

-- Index for comorbidity searches
CREATE INDEX IF NOT EXISTS idx_semantic_graph_pathologies 
ON semantic_graph_cache USING GIN (pathologies);

-- RLS policies
ALTER TABLE semantic_graph_cache ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read from cache (it's shared knowledge)
CREATE POLICY "semantic_graph_cache_read" ON semantic_graph_cache
    FOR SELECT USING (true);

-- Allow authenticated users to insert/update
CREATE POLICY "semantic_graph_cache_insert" ON semantic_graph_cache
    FOR INSERT WITH CHECK (true);

CREATE POLICY "semantic_graph_cache_update" ON semantic_graph_cache
    FOR UPDATE USING (true);

-- Function to normalize topic for matching
CREATE OR REPLACE FUNCTION normalize_topic(topic TEXT)
RETURNS TEXT AS $$
BEGIN
    RETURN lower(
        regexp_replace(
            unaccent(trim(topic)),
            '[^a-z0-9\s]', '', 'gi'
        )
    );
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Function to get or create cache entry
CREATE OR REPLACE FUNCTION get_cached_graph(p_topic TEXT)
RETURNS TABLE(
    id UUID,
    topic TEXT,
    nodes JSONB,
    edges JSONB,
    sources_consulted JSONB,
    hit_count INTEGER,
    created_at TIMESTAMPTZ
) AS $$
DECLARE
    v_normalized TEXT;
BEGIN
    v_normalized := normalize_topic(p_topic);
    
    -- Update hit count if found
    UPDATE semantic_graph_cache c
    SET hit_count = c.hit_count + 1, updated_at = NOW()
    WHERE c.topic_normalized = v_normalized;
    
    -- Return cached data
    RETURN QUERY
    SELECT c.id, c.topic, c.nodes, c.edges, c.sources_consulted, c.hit_count, c.created_at
    FROM semantic_graph_cache c
    WHERE c.topic_normalized = v_normalized;
END;
$$ LANGUAGE plpgsql;

COMMENT ON TABLE semantic_graph_cache IS 'Cache for semantic graph nodes generated by Claude to improve subsequent query performance';
