-- Add indexes to unindexed foreign keys to improve join performance
CREATE INDEX IF NOT EXISTS idx_alert_rules_created_by ON public.alert_rules(created_by);
CREATE INDEX IF NOT EXISTS idx_cde_analysis_runs_created_by ON public.cde_analysis_runs(created_by);
CREATE INDEX IF NOT EXISTS idx_cde_pair_analyses_substance_a ON public.cde_pair_analyses(substance_a_id);
CREATE INDEX IF NOT EXISTS idx_cde_pair_analyses_substance_b ON public.cde_pair_analyses(substance_b_id);
CREATE INDEX IF NOT EXISTS idx_discovery_cards_reviewed_by ON public.discovery_cards(reviewed_by);
CREATE INDEX IF NOT EXISTS idx_discovery_ev_snippets_paper ON public.discovery_evidence_snippets(paper_id);
CREATE INDEX IF NOT EXISTS idx_drug_compositions_substance ON public.drug_compositions(substance_id);
CREATE INDEX IF NOT EXISTS idx_frontier_jobs_hypothesis ON public.frontier_jobs(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_graph_audit_log_hypothesis ON public.graph_audit_log(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_graph_cache_central_node ON public.graph_cache(central_node_id);
CREATE INDEX IF NOT EXISTS idx_kg_causal_rules_validated_by ON public.kg_causal_rules(validated_by);
CREATE INDEX IF NOT EXISTS idx_lbd_claim_evidence_claim ON public.lbd_claim_evidence(claim_id);
CREATE INDEX IF NOT EXISTS idx_lbd_claim_evidence_passage ON public.lbd_claim_evidence(passage_id);
CREATE INDEX IF NOT EXISTS idx_lbd_claims_hypothesis ON public.lbd_claims(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_lbd_contradictions_refute ON public.lbd_contradictions(claim_refute_id);
CREATE INDEX IF NOT EXISTS idx_lbd_contradictions_support ON public.lbd_contradictions(claim_support_id);
CREATE INDEX IF NOT EXISTS idx_medical_sources_pathology ON public.medical_sources(pathology_id);
CREATE INDEX IF NOT EXISTS idx_pathology_symptoms_symptom ON public.pathology_symptoms(symptom_id);
CREATE INDEX IF NOT EXISTS idx_patient_alerts_acknowledged ON public.patient_alerts(acknowledged_by);
CREATE INDEX IF NOT EXISTS idx_patient_alerts_resolved ON public.patient_alerts(resolved_by);
CREATE INDEX IF NOT EXISTS idx_patient_alerts_rule ON public.patient_alerts(rule_id);
CREATE INDEX IF NOT EXISTS idx_patient_symptoms_source_doc ON public.patient_symptoms(source_document_id);
CREATE INDEX IF NOT EXISTS idx_patients_pathology ON public.patients(pathology_id);
CREATE INDEX IF NOT EXISTS idx_rec_templates_created_by ON public.recommendation_templates(created_by);
CREATE INDEX IF NOT EXISTS idx_rec_log_implemented_by ON public.recommendations_log(implemented_by);
CREATE INDEX IF NOT EXISTS idx_rec_log_outcome_rec_by ON public.recommendations_log(outcome_recorded_by);
CREATE INDEX IF NOT EXISTS idx_rec_log_reviewed_by ON public.recommendations_log(reviewed_by);
CREATE INDEX IF NOT EXISTS idx_side_effect_alerts_patient ON public.side_effect_alerts(patient_id);
CREATE INDEX IF NOT EXISTS idx_side_effect_alerts_reviewed ON public.side_effect_alerts(reviewed_by);
CREATE INDEX IF NOT EXISTS idx_side_effect_alerts_medication ON public.side_effect_alerts(suspected_medication_id);

-- Remove unused indexes to save storage and maintenance overhead
DROP INDEX IF EXISTS idx_drug_equivalences_category;
DROP INDEX IF EXISTS idx_substances_allergen;
DROP INDEX IF EXISTS idx_drug_equivalences_drug_name;
DROP INDEX IF EXISTS idx_drug_switch_protocols_category;
DROP INDEX IF EXISTS idx_drug_switch_protocols_from_drug;
DROP INDEX IF EXISTS idx_symptoms_category;
DROP INDEX IF EXISTS idx_drug_switch_protocols_to_drug;
DROP INDEX IF EXISTS idx_pathologies_name_lower;
DROP INDEX IF EXISTS idx_recommendations_patient;
DROP INDEX IF EXISTS idx_recommendations_status;
DROP INDEX IF EXISTS idx_recommendations_type;
DROP INDEX IF EXISTS idx_recommendations_created;
DROP INDEX IF EXISTS idx_recommendations_urgency;
DROP INDEX IF EXISTS idx_symptoms_ncbi_id;
DROP INDEX IF EXISTS idx_pathologies_ncbi_id;
DROP INDEX IF EXISTS idx_medications_ncbi_id;
DROP INDEX IF EXISTS idx_nodes_category;
DROP INDEX IF EXISTS idx_alert_rules_category;
DROP INDEX IF EXISTS idx_alert_rules_enabled;
DROP INDEX IF EXISTS idx_patient_alerts_patient;
DROP INDEX IF EXISTS idx_patient_alerts_status;
DROP INDEX IF EXISTS idx_patient_alerts_level;
DROP INDEX IF EXISTS idx_patient_alerts_created;
DROP INDEX IF EXISTS idx_alert_subscriptions_user;
DROP INDEX IF EXISTS idx_medications_atc_code;
DROP INDEX IF EXISTS idx_medications_substance;
DROP INDEX IF EXISTS idx_medications_pharmacode;
DROP INDEX IF EXISTS idx_patients_last_name;
DROP INDEX IF EXISTS idx_patients_first_name;
DROP INDEX IF EXISTS idx_patients_date_of_birth;
DROP INDEX IF EXISTS idx_nodes_tags_gin;
DROP INDEX IF EXISTS idx_cde_nodes_external_id;
DROP INDEX IF EXISTS idx_cde_nodes_embedding;
DROP INDEX IF EXISTS idx_cde_edges_weight;
DROP INDEX IF EXISTS idx_medications_gtin;
DROP INDEX IF EXISTS idx_medications_atc;
DROP INDEX IF EXISTS idx_medications_swissmedic_number;
DROP INDEX IF EXISTS idx_cde_edges_activation;
DROP INDEX IF EXISTS idx_patient_medications_patient;
DROP INDEX IF EXISTS idx_patient_medications_medication;
DROP INDEX IF EXISTS idx_patient_medications_active;
DROP INDEX IF EXISTS idx_cde_nodes_substance_id;
DROP INDEX IF EXISTS idx_symptoms_embedding;
DROP INDEX IF EXISTS idx_semantic_links_similarity;
DROP INDEX IF EXISTS idx_causal_links_from;
DROP INDEX IF EXISTS idx_causal_links_to;
DROP INDEX IF EXISTS idx_causal_links_pair_hash;
DROP INDEX IF EXISTS idx_causal_links_types;
DROP INDEX IF EXISTS idx_analysis_cache_hash;
DROP INDEX IF EXISTS idx_pathologies_embedding;
DROP INDEX IF EXISTS idx_symptoms_name_lower;
DROP INDEX IF EXISTS idx_treatments_name_lower;
DROP INDEX IF EXISTS idx_treatments_embedding;
DROP INDEX IF EXISTS idx_recommendation_actions_rec;
DROP INDEX IF EXISTS idx_medications_category;
DROP INDEX IF EXISTS idx_medications_name_lower;
DROP INDEX IF EXISTS idx_recommendation_actions_type;
DROP INDEX IF EXISTS idx_medications_embedding;
DROP INDEX IF EXISTS idx_recommendation_actions_by;
DROP INDEX IF EXISTS idx_patient_documents_category;
DROP INDEX IF EXISTS idx_patient_documents_status;
DROP INDEX IF EXISTS idx_kg_enzymes_name;
DROP INDEX IF EXISTS idx_kg_enzyme_medication_enzyme;
DROP INDEX IF EXISTS idx_kg_enzyme_medication_med;
DROP INDEX IF EXISTS idx_kg_enzyme_medication_type;
DROP INDEX IF EXISTS idx_kg_causal_rules_source;
DROP INDEX IF EXISTS idx_kg_causal_rules_target;
DROP INDEX IF EXISTS idx_kg_causal_rules_relation;
DROP INDEX IF EXISTS idx_kg_causal_rules_validated;
DROP INDEX IF EXISTS idx_kg_population_factors_type;
DROP INDEX IF EXISTS idx_cde_edges_provenance;
DROP INDEX IF EXISTS idx_cde_edges_type;
DROP INDEX IF EXISTS cde_nodes_embedding_idx;
DROP INDEX IF EXISTS idx_semantic_graph_pathologies;
DROP INDEX IF EXISTS idx_semantic_graph_topic_normalized;
DROP INDEX IF EXISTS idx_patient_medications_doc;
DROP INDEX IF EXISTS kg_embeddings_embedding_idx;
DROP INDEX IF EXISTS idx_drug_compositions_med;
DROP INDEX IF EXISTS idx_drug_compositions_molecule;
DROP INDEX IF EXISTS idx_allergens_name;
DROP INDEX IF EXISTS idx_allergens_category;
DROP INDEX IF EXISTS idx_foods_name;
DROP INDEX IF EXISTS idx_food_drug_interactions_food;
DROP INDEX IF EXISTS idx_food_drug_interactions_med;
DROP INDEX IF EXISTS idx_alternative_treatments_name;
DROP INDEX IF EXISTS idx_alternative_treatments_type;
DROP INDEX IF EXISTS idx_clinical_trials_nct;
DROP INDEX IF EXISTS idx_clinical_trials_status;
DROP INDEX IF EXISTS idx_clinical_trials_conditions;
DROP INDEX IF EXISTS idx_discovery_cards_severity;
DROP INDEX IF EXISTS idx_discovery_cards_status;
DROP INDEX IF EXISTS idx_med_sub_medication;
DROP INDEX IF EXISTS idx_med_sub_substance;
DROP INDEX IF EXISTS idx_focused_research_user;
DROP INDEX IF EXISTS idx_focused_research_target;
DROP INDEX IF EXISTS idx_focused_research_status;
DROP INDEX IF EXISTS idx_focused_research_created;
DROP INDEX IF EXISTS idx_focused_research_search;
DROP INDEX IF EXISTS idx_categories_parent;
DROP INDEX IF EXISTS idx_categories_node_type;
DROP INDEX IF EXISTS idx_categories_code_prefix;
DROP INDEX IF EXISTS idx_analysis_runs_status;
DROP INDEX IF EXISTS idx_cde_nodes_name;
DROP INDEX IF EXISTS idx_node_links_source;
DROP INDEX IF EXISTS idx_node_links_target;
DROP INDEX IF EXISTS idx_node_links_type;
DROP INDEX IF EXISTS idx_pair_analyses_discovery;
DROP INDEX IF EXISTS idx_molecules_name;
DROP INDEX IF EXISTS idx_molecules_type;
DROP INDEX IF EXISTS idx_substances_name;
DROP INDEX IF EXISTS idx_cde_discoveries_type;
DROP INDEX IF EXISTS idx_cde_discoveries_severity;
DROP INDEX IF EXISTS idx_cde_discoveries_pathology;
DROP INDEX IF EXISTS idx_discovery_validation_status;
DROP INDEX IF EXISTS idx_cde_discoveries_status;
DROP INDEX IF EXISTS idx_validation_logs_discovery;
DROP INDEX IF EXISTS idx_validation_logs_valid;
DROP INDEX IF EXISTS idx_cde_nodes_category;
DROP INDEX IF EXISTS idx_user_edges_user;
DROP INDEX IF EXISTS idx_user_edges_analyzed;
DROP INDEX IF EXISTS idx_pubmed_pmid;
DROP INDEX IF EXISTS idx_pubmed_mesh;
DROP INDEX IF EXISTS idx_semantic_nodes_type;
DROP INDEX IF EXISTS idx_semantic_nodes_label;
DROP INDEX IF EXISTS idx_semantic_nodes_source;
DROP INDEX IF EXISTS idx_semantic_edges_source;
DROP INDEX IF EXISTS idx_semantic_edges_target;
DROP INDEX IF EXISTS idx_discovery_feedback_discovery;
DROP INDEX IF EXISTS idx_discovery_feedback_user;
DROP INDEX IF EXISTS idx_discovery_feedback_type;
DROP INDEX IF EXISTS idx_discovery_feedback_created;
DROP INDEX IF EXISTS idx_semantic_edges_type;
DROP INDEX IF EXISTS idx_ml_patterns_type;
DROP INDEX IF EXISTS idx_ml_patterns_key;
DROP INDEX IF EXISTS idx_ml_patterns_relevance;
DROP INDEX IF EXISTS idx_ml_recommendations_user;
DROP INDEX IF EXISTS idx_ml_recommendations_context;
DROP INDEX IF EXISTS idx_ml_recommendations_expires;
DROP INDEX IF EXISTS idx_graph_cache_accessed;
DROP INDEX IF EXISTS idx_graph_cache_version;
DROP INDEX IF EXISTS idx_discovery_alerts_user_id;
DROP INDEX IF EXISTS idx_discovery_alerts_unread;
DROP INDEX IF EXISTS idx_discovery_alerts_type;
DROP INDEX IF EXISTS idx_discovery_alerts_created_at;
DROP INDEX IF EXISTS idx_discovery_subscriptions_user_id;
DROP INDEX IF EXISTS idx_discovery_subscriptions_next_run;
